/**
 * API Hata Kodları
 * Backend ve Mobil'de ortak kullanılan hata kodları
 */
export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  // Product
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  INVALID_BARCODE: "INVALID_BARCODE",
  MAX_VARIANTS_REACHED: "MAX_VARIANTS_REACHED",

  // AI
  AI_SERVICE_ERROR: "AI_SERVICE_ERROR",
  AI_PARSE_ERROR: "AI_PARSE_ERROR",

  // General
  RATE_LIMIT: "RATE_LIMIT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
} as const;

/**
 * Hata kodu tipi
 */
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
